import { prisma } from './prisma';

const districtsByState: { stateName: string; stateId: number; districts: { code: string; name: string }[] }[] = [
  {
    stateName: 'Sikkim',
    stateId: 11,
    districts: [
      { code: '01', name: 'North District' },
      { code: '02', name: 'West District' },
      { code: '03', name: 'South District' },
      { code: '04', name: 'East District' },
    ],
  },
  {
    stateName: 'Arunachal Pradesh',
    stateId: 12,
    districts: [
      { code: '01', name: 'Tawang' },
      { code: '02', name: 'West Kameng' },
      { code: '03', name: 'East Kameng' },
      { code: '04', name: 'Papum Pare' },
      { code: '05', name: 'Upper Subansiri' },
      { code: '06', name: 'West Siang' },
      { code: '07', name: 'East Siang' },
      { code: '08', name: 'Upper Siang' },
      { code: '09', name: 'Changlang' },
      { code: '10', name: 'Tirap' },
      { code: '11', name: 'Lower Subansiri' },
      { code: '12', name: 'Kurung Kumey' },
      { code: '13', name: 'Dibang Valley' },
      { code: '14', name: 'Lower Dibang Valley' },
      { code: '15', name: 'Lohit' },
      { code: '16', name: 'Anjaw' },
    ],
  },
  {
    stateName: 'Nagaland',
    stateId: 13,
    districts: [
      { code: '01', name: 'Mon' },
      { code: '02', name: 'Mokokchung' },
      { code: '03', name: 'Zunheboto' },
      { code: '04', name: 'Wokha' },
      { code: '05', name: 'Dimapur' },
      { code: '06', name: 'Phek' },
      { code: '07', name: 'Tuensang' },
      { code: '08', name: 'Longleng' },
      { code: '09', name: 'Kiphire' },
      { code: '10', name: 'Kohima' },
      { code: '11', name: 'Peren' },
    ],
  },
  {
    stateName: 'Manipur',
    stateId: 14,
    districts: [
      { code: '01', name: 'Senapati' },
      { code: '02', name: 'Tamenglong' },
      { code: '03', name: 'Churachandpur' },
      { code: '04', name: 'Bishnupur' },
      { code: '05', name: 'Thoubal' },
      { code: '06', name: 'Imphal West' },
      { code: '07', name: 'Imphal East' },
      { code: '08', name: 'Ukhrul' },
      { code: '09', name: 'Chandel' },
    ],
  },
  {
    stateName: 'Mizoram',
    stateId: 15,
    districts: [
      { code: '01', name: 'Mamit' },
      { code: '02', name: 'Kolasib' },
      { code: '03', name: 'Aizawl' },
      { code: '04', name: 'Champhai' },
      { code: '05', name: 'Serchhip' },
      { code: '06', name: 'Lunglei' },
      { code: '07', name: 'Lawngtlai' },
      { code: '08', name: 'Saiha' },
    ],
  },
  {
    stateName: 'Tripura',
    stateId: 16,
    districts: [
      { code: '01', name: 'West Tripura' },
      { code: '02', name: 'South Tripura' },
      { code: '03', name: 'Dhalai' },
      { code: '04', name: 'North Tripura' },
    ],
  },
  {
    stateName: 'Meghalaya',
    stateId: 17,
    districts: [
      { code: '01', name: 'West Garo Hills' },
      { code: '02', name: 'East Garo Hills' },
      { code: '03', name: 'South Garo Hills' },
      { code: '04', name: 'West Khasi Hills' },
      { code: '05', name: 'Ribhoi' },
      { code: '06', name: 'East Khasi Hills' },
      { code: '07', name: 'Jaintia Hills' },
    ],
  },
  {
    stateName: 'Jharkhand',
    stateId: 20,
    districts: [
      { code: '01', name: 'Garhwa' },
      { code: '02', name: 'Chatra' },
      { code: '03', name: 'Kodarma' },
      { code: '04', name: 'Giridih' },
      { code: '05', name: 'Deoghar' },
      { code: '06', name: 'Godda' },
      { code: '07', name: 'Sahibganj' },
      { code: '08', name: 'Pakur' },
      { code: '09', name: 'Dhanbad' },
      { code: '10', name: 'Bokaro' },
      { code: '11', name: 'Lohardaga' },
      { code: '12', name: 'Purbi Singhbhum' },
      { code: '13', name: 'Palamu' },
      { code: '14', name: 'Latehar' },
      { code: '15', name: 'Hazaribagh' },
      { code: '16', name: 'Ramgarh' },
      { code: '17', name: 'Dumka' },
      { code: '18', name: 'Jamtara' },
      { code: '19', name: 'Ranchi' },
      { code: '20', name: 'Khunti' },
      { code: '21', name: 'Gumla' },
      { code: '22', name: 'Simdega' },
      { code: '23', name: 'Pashchimi Singhbhum' },
      { code: '24', name: 'Saraikela-Kharsawan' },
    ],
  },
  {
    stateName: 'Odisha',
    stateId: 21,
    districts: [
      { code: '01', name: 'Bargarh' },
      { code: '02', name: 'Jharsuguda' },
      { code: '03', name: 'Sambalpur' },
      { code: '04', name: 'Debagarh' },
      { code: '05', name: 'Sundargarh' },
      { code: '06', name: 'Kendujhar' },
      { code: '07', name: 'Mayurbhanj' },
      { code: '08', name: 'Baleshwar' },
      { code: '09', name: 'Bhadrak' },
      { code: '10', name: 'Kendrapara' },
      { code: '11', name: 'Jagatsinghapur' },
      { code: '12', name: 'Cuttack' },
      { code: '13', name: 'Jajapur' },
      { code: '14', name: 'Dhenkanal' },
      { code: '15', name: 'Anugul' },
      { code: '16', name: 'Nayagarh' },
      { code: '17', name: 'Khordha' },
      { code: '18', name: 'Puri' },
      { code: '19', name: 'Ganjam' },
      { code: '20', name: 'Gajapati' },
      { code: '21', name: 'Kandhamal' },
      { code: '22', name: 'Baudh' },
      { code: '23', name: 'Subarnapur' },
      { code: '24', name: 'Balangir' },
      { code: '25', name: 'Nuapada' },
      { code: '26', name: 'Kalahandi' },
      { code: '27', name: 'Rayagada' },
      { code: '28', name: 'Nabarangapur' },
      { code: '29', name: 'Koraput' },
      { code: '30', name: 'Malkangiri' },
    ],
  },
  {
    stateName: 'Bihar',
    stateId: 10,
    districts: [
      { code: '01', name: 'Pashchim Champaran' },
      { code: '02', name: 'Purba Champaran' },
      { code: '03', name: 'Sheohar' },
      { code: '04', name: 'Sitamarhi' },
      { code: '05', name: 'Madhubani' },
      { code: '06', name: 'Supaul' },
      { code: '07', name: 'Araria' },
      { code: '08', name: 'Kishanganj' },
      { code: '09', name: 'Purnia' },
      { code: '10', name: 'Katihar' },
      { code: '11', name: 'Madhepura' },
      { code: '12', name: 'Saharsa' },
      { code: '13', name: 'Darbhanga' },
      { code: '14', name: 'Muzaffarpur' },
      { code: '15', name: 'Gopalganj' },
      { code: '16', name: 'Siwan' },
      { code: '17', name: 'Saran' },
      { code: '18', name: 'Vaishali' },
      { code: '19', name: 'Samastipur' },
      { code: '20', name: 'Begusarai' },
      { code: '21', name: 'Khagaria' },
      { code: '22', name: 'Bhagalpur' },
      { code: '23', name: 'Banka' },
      { code: '24', name: 'Munger' },
      { code: '25', name: 'Lakhisarai' },
      { code: '26', name: 'Sheikhpura' },
      { code: '27', name: 'Nalanda' },
      { code: '28', name: 'Patna' },
      { code: '29', name: 'Bhojpur' },
      { code: '30', name: 'Buxar' },
      { code: '31', name: 'Kaimur (Bhabua)' },
      { code: '32', name: 'Rohtas' },
      { code: '33', name: 'Aurangabad' },
      { code: '34', name: 'Gaya' },
      { code: '35', name: 'Nawada' },
      { code: '36', name: 'Jamui' },
      { code: '37', name: 'Jehanabad' },
      { code: '38', name: 'Arwal' },
    ],
  },
  {
    stateName: 'Assam',
    stateId: 18,
    districts: [
      { code: '01', name: 'Kokrajhar' },
      { code: '02', name: 'Dhubri' },
      { code: '03', name: 'Goalpara' },
      { code: '04', name: 'Barpeta' },
      { code: '05', name: 'Morigaon' },
      { code: '06', name: 'Nagaon' },
      { code: '07', name: 'Sonitpur' },
      { code: '08', name: 'Lakhimpur' },
      { code: '09', name: 'Dhemaji' },
      { code: '10', name: 'Tinsukia' },
      { code: '11', name: 'Dibrugarh' },
      { code: '12', name: 'Sivasagar' },
      { code: '13', name: 'Jorhat' },
      { code: '14', name: 'Golaghat' },
      { code: '15', name: 'Karbi Anglong' },
      { code: '16', name: 'Dima Hasao' },
      { code: '17', name: 'Cachar' },
      { code: '18', name: 'Karimganj' },
      { code: '19', name: 'Hailakandi' },
      { code: '20', name: 'Bongaigaon' },
      { code: '21', name: 'Chirang' },
      { code: '22', name: 'Kamrup' },
      { code: '23', name: 'Kamrup Metropolitan' },
      { code: '24', name: 'Nalbari' },
      { code: '25', name: 'Baksa' },
      { code: '26', name: 'Darrang' },
      { code: '27', name: 'Udalguri' },
    ],
  },
  {
    stateName: 'West Bengal',
    stateId: 19,
    districts: [
      { code: '01', name: 'Darjiling' },
      { code: '02', name: 'Jalpaiguri' },
      { code: '03', name: 'Kochbihar' },
      { code: '04', name: 'Uttardinajpur' },
      { code: '05', name: 'Dakshin Dinajpur' },
      { code: '06', name: 'Maldah' },
      { code: '07', name: 'Murshidabad' },
      { code: '08', name: 'Birbhum' },
      { code: '09', name: 'Barddhaman' },
      { code: '10', name: 'Nadia' },
      { code: '11', name: 'North Twenty Four Parganas' },
      { code: '12', name: 'Hugli' },
      { code: '13', name: 'Bankura' },
      { code: '14', name: 'Puruliya' },
      { code: '15', name: 'Haora' },
      { code: '16', name: 'Kolkata' },
      { code: '17', name: 'South Twenty Four Parganas' },
      { code: '18', name: 'Paschim Medinipur' },
      { code: '19', name: 'Purbamedinipur' },
    ],
  },
  {
    stateName: 'Jammu & Kashmir',
    stateId: 1,
    districts: [
      { code: '01', name: 'Kupwara' },
      { code: '02', name: 'Badgam' },
      { code: '03', name: 'Leh(Ladakh)' },
      { code: '04', name: 'Kargil' },
      { code: '05', name: 'Punch' },
      { code: '06', name: 'Rajouri' },
      { code: '07', name: 'Kathua' },
      { code: '08', name: 'Baramula' },
      { code: '09', name: 'Bandipore' },
      { code: '10', name: 'Srinagar' },
      { code: '11', name: 'Ganderbal' },
      { code: '12', name: 'Pulwama' },
      { code: '13', name: 'Shupiyan' },
      { code: '14', name: 'Anantnag' },
      { code: '15', name: 'Kulgam' },
      { code: '16', name: 'Doda' },
      { code: '17', name: 'Ramban' },
      { code: '18', name: 'Kishtwar' },
      { code: '19', name: 'Udhampur' },
      { code: '20', name: 'Reasi' },
      { code: '21', name: 'Jammu' },
      { code: '22', name: 'Samba' },
    ],
  },
  {
    stateName: 'Himachal Pradesh',
    stateId: 2,
    districts: [
      { code: '01', name: 'Chamba' },
      { code: '02', name: 'Kangra' },
      { code: '03', name: 'Lahul & Spiti' },
      { code: '04', name: 'Kullu' },
      { code: '05', name: 'Mandi' },
      { code: '06', name: 'Hamirpur' },
      { code: '07', name: 'Una' },
      { code: '08', name: 'Bilaspur' },
      { code: '09', name: 'Solan' },
      { code: '10', name: 'Sirmaur' },
      { code: '11', name: 'Shimla' },
      { code: '12', name: 'Kinnaur' },
    ],
  },
  {
    stateName: 'Chandigarh',
    stateId: 4,
    districts: [{ code: '01', name: 'Chandigarh District' }],
  },
  {
    stateName: 'Rajasthan',
    stateId: 8,
    districts: [
      { code: '01', name: 'Ganganagar' },
      { code: '02', name: 'Hanumangarh' },
      { code: '03', name: 'Bikaner' },
      { code: '04', name: 'Churu' },
      { code: '05', name: 'Jhunjhununu' },
      { code: '06', name: 'Alwar' },
      { code: '07', name: 'Bharatpur' },
      { code: '08', name: 'Dhaulpur' },
      { code: '09', name: 'Karauli' },
      { code: '10', name: 'Sawai Madhopur' },
      { code: '11', name: 'Dausa' },
      { code: '12', name: 'Jaipur' },
      { code: '13', name: 'Sikar' },
      { code: '14', name: 'Nagaur' },
      { code: '15', name: 'Jodhpur' },
      { code: '16', name: 'Jaisalmer' },
      { code: '17', name: 'Barmer' },
      { code: '18', name: 'Jalor' },
      { code: '19', name: 'Sirohi' },
      { code: '20', name: 'Pali' },
      { code: '21', name: 'Ajmer' },
      { code: '22', name: 'Tonk' },
      { code: '23', name: 'Bundi' },
      { code: '24', name: 'Bhilwara' },
      { code: '25', name: 'Rajsamand' },
      { code: '26', name: 'Dungarpur' },
      { code: '27', name: 'Banswara' },
      { code: '28', name: 'Chittaurgarh' },
      { code: '29', name: 'Kota' },
      { code: '30', name: 'Baran' },
      { code: '31', name: 'Jhalawar' },
      { code: '32', name: 'Udaipur' },
      { code: '33', name: 'Pratapgarh' },
    ],
  },
  {
    stateName: 'Uttar Pradesh',
    stateId: 9,
    districts: [
      { code: '01', name: 'Saharanpur' },
      { code: '02', name: 'Muzaffarnagar' },
      { code: '03', name: 'Bijnor' },
      { code: '04', name: 'Moradabad' },
      { code: '05', name: 'Rampur' },
      { code: '06', name: 'Jyotiba Phule Nagar' },
      { code: '07', name: 'Meerut' },
      { code: '08', name: 'Baghpat' },
      { code: '09', name: 'Ghaziabad' },
      { code: '10', name: 'Gautam Buddha Nagar' },
      { code: '11', name: 'Bulandshahr' },
      { code: '12', name: 'Aligarh' },
      { code: '13', name: 'Mahamaya Nagar' },
      { code: '14', name: 'Mathura' },
      { code: '15', name: 'Agra' },
      { code: '16', name: 'Firozabad' },
      { code: '17', name: 'Mainpuri' },
      { code: '18', name: 'Budaun' },
      { code: '19', name: 'Bareilly' },
      { code: '20', name: 'Pilibhit' },
      { code: '21', name: 'Shahjahanpur' },
      { code: '22', name: 'Kheri' },
      { code: '23', name: 'Sitapur' },
      { code: '24', name: 'Hardoi' },
      { code: '25', name: 'Unnao' },
      { code: '26', name: 'Lucknow' },
      { code: '27', name: 'Rae Bareli' },
      { code: '28', name: 'Farrukhabad' },
      { code: '29', name: 'Kannauj' },
      { code: '30', name: 'Etawah' },
      { code: '31', name: 'Auraiya' },
      { code: '32', name: 'Kanpur Dehat' },
      { code: '33', name: 'Kanpur Nagar' },
      { code: '34', name: 'Jalaun' },
      { code: '35', name: 'Jhansi' },
      { code: '36', name: 'Lalitpur' },
      { code: '37', name: 'Hamirpur' },
      { code: '38', name: 'Mahoba' },
      { code: '39', name: 'Banda' },
      { code: '40', name: 'Chitrakoot' },
      { code: '41', name: 'Fatehpur' },
      { code: '42', name: 'Pratapgarh' },
      { code: '43', name: 'Kaushambi' },
      { code: '44', name: 'Allahabad' },
      { code: '45', name: 'Bara Banki' },
      { code: '46', name: 'Faizabad' },
      { code: '47', name: 'Ambedkar Nagar' },
      { code: '48', name: 'Sultanpur' },
      { code: '49', name: 'Bahraich' },
      { code: '50', name: 'Shrawasti' },
      { code: '51', name: 'Balrampur' },
      { code: '52', name: 'Gonda' },
      { code: '53', name: 'Siddharthnagar' },
      { code: '54', name: 'Basti' },
      { code: '55', name: 'Sant Kabir Nagar' },
      { code: '56', name: 'Mahrajganj' },
      { code: '57', name: 'Gorakhpur' },
      { code: '58', name: 'Kushinagar' },
      { code: '59', name: 'Deoria' },
      { code: '60', name: 'Azamgarh' },
      { code: '61', name: 'Mau' },
      { code: '62', name: 'Ballia' },
      { code: '63', name: 'Jaunpur' },
      { code: '64', name: 'Ghazipur' },
      { code: '65', name: 'Chandauli' },
      { code: '66', name: 'Varanasi' },
      { code: '67', name: 'Sant Ravidas Nagar (Bhadohi)' },
      { code: '68', name: 'Mirzapur' },
      { code: '69', name: 'Sonbhadra' },
      { code: '70', name: 'Etah' },
      { code: '71', name: 'Kanshiram Nagar' },
    ],
  },
  {
    stateName: 'Punjab',
    stateId: 3,
    districts: [
      { code: '01', name: 'Gurdaspur' },
      { code: '02', name: 'Kapurthala' },
      { code: '03', name: 'Jalandhar' },
      { code: '04', name: 'Hoshiarpur' },
      { code: '05', name: 'Shahid Bhagat' },
      { code: '06', name: 'Fatehgarh Sahib' },
      { code: '07', name: 'Ludhiana' },
      { code: '08', name: 'Moga' },
      { code: '09', name: 'Firozpur' },
      { code: '10', name: 'Muktsar' },
      { code: '11', name: 'Faridkot' },
      { code: '12', name: 'Bathinda' },
      { code: '13', name: 'Mansa' },
      { code: '14', name: 'Patiala' },
      { code: '15', name: 'Amritsar' },
      { code: '16', name: 'Tarn Taran' },
      { code: '17', name: 'Rupnagar' },
      { code: '18', name: 'Sahibzada Ajit Singh Nagar' },
      { code: '19', name: 'Sangrur' },
      { code: '20', name: 'Barnala' },
    ],
  },
  {
    stateName: 'Uttarakhand',
    stateId: 5,
    districts: [
      { code: '01', name: 'Uttarkashi' },
      { code: '02', name: 'Chamoli' },
      { code: '03', name: 'Rudraprayag' },
      { code: '04', name: 'Tehri Garhwal' },
      { code: '05', name: 'Dehradun' },
      { code: '06', name: 'Garhwal' },
      { code: '07', name: 'Pithoragarh' },
      { code: '08', name: 'Almora' },
      { code: '09', name: 'Champawat' },
      { code: '10', name: 'Nainital' },
      { code: '11', name: 'Udham Singh Nagar' },
      { code: '12', name: 'Haridwar' },
    ],
  },
  {
    stateName: 'Haryana',
    stateId: 6,
    districts: [
      { code: '01', name: 'Panchkula' },
      { code: '02', name: 'Ambala' },
      { code: '03', name: 'Yamunanagar' },
      { code: '04', name: 'Kurukshetra' },
      { code: '05', name: 'Kaithal' },
      { code: '06', name: 'Karnal' },
      { code: '07', name: 'Panipat' },
      { code: '08', name: 'Sonipat' },
      { code: '09', name: 'Jind' },
      { code: '10', name: 'Fatehabad' },
      { code: '11', name: 'Sirsa' },
      { code: '12', name: 'Hisar' },
      { code: '13', name: 'Bhiwani' },
      { code: '14', name: 'Rohtak' },
      { code: '15', name: 'Jhajjar' },
      { code: '16', name: 'Mahendragarh' },
      { code: '17', name: 'Rewari' },
      { code: '18', name: 'Gurgaon' },
      { code: '19', name: 'Mewat' },
      { code: '20', name: 'Faridabad' },
      { code: '21', name: 'Palwal' },
    ],
  },
  {
    stateName: 'Delhi',
    stateId: 7,
    districts: [
      { code: '01', name: 'North West' },
      { code: '02', name: 'North' },
      { code: '03', name: 'North East' },
      { code: '04', name: 'East' },
      { code: '05', name: 'New Delhi' },
      { code: '06', name: 'Central Delhi' },
      { code: '07', name: 'West' },
      { code: '08', name: 'South West' },
      { code: '09', name: 'South' },
      { code: '10', name: 'Shahdra' },
      { code: '11', name: 'South East' },
    ],
  },
  {
    stateName: 'Kerala',
    stateId: 32,
    districts: [
      { code: '01', name: 'Kasaragod' },
      { code: '02', name: 'Kannur' },
      { code: '03', name: 'Wayanad' },
      { code: '04', name: 'Kozhikode' },
      { code: '05', name: 'Malappuram' },
      { code: '06', name: 'Palakkad' },
      { code: '07', name: 'Thrissur' },
      { code: '08', name: 'Ernakulam' },
      { code: '09', name: 'Idukki' },
      { code: '10', name: 'Kottayam' },
      { code: '11', name: 'Alappuzha' },
      { code: '12', name: 'Pathanamthitta' },
      { code: '13', name: 'Kollam' },
      { code: '14', name: 'Thiruvananthapuram' },
    ],
  },
  {
    stateName: 'Tamil Nadu',
    stateId: 33,
    districts: [
      { code: '01', name: 'Thiruvallur' },
      { code: '02', name: 'Chennai' },
      { code: '03', name: 'Kancheepuram' },
      { code: '04', name: 'Vellore' },
      { code: '05', name: 'Tiruvannamalai' },
      { code: '06', name: 'Viluppuram' },
      { code: '07', name: 'Salem' },
      { code: '08', name: 'Namakkal' },
      { code: '09', name: 'Erode' },
      { code: '10', name: 'The Nilgiris' },
      { code: '11', name: 'Dindigul' },
      { code: '12', name: 'Karur' },
      { code: '13', name: 'Tiruchirappalli' },
      { code: '14', name: 'Perambalur' },
      { code: '15', name: 'Ariyalur' },
      { code: '16', name: 'Cuddalore' },
      { code: '17', name: 'Nagapattinam' },
      { code: '18', name: 'Thiruvarur' },
      { code: '19', name: 'Thanjavur' },
      { code: '20', name: 'Pudukkottai' },
      { code: '21', name: 'Sivaganga' },
      { code: '22', name: 'Madurai' },
      { code: '23', name: 'Theni' },
      { code: '24', name: 'Virudhunagar' },
      { code: '25', name: 'Ramanathapuram' },
      { code: '26', name: 'Thoothukkudi' },
      { code: '27', name: 'Tirunelveli' },
      { code: '28', name: 'Kanniyakumari' },
      { code: '29', name: 'Dharmapuri' },
      { code: '30', name: 'Krishnagiri' },
      { code: '31', name: 'Coimbatore' },
      { code: '32', name: 'Tiruppur' },
    ],
  },
  {
    stateName: 'Telangana',
    stateId: 36,
    districts: [
      { code: '01', name: 'Adilabad' },
      { code: '02', name: 'Nizamabad' },
      { code: '03', name: 'Karimnagar' },
      { code: '04', name: 'Medak' },
      { code: '05', name: 'Hyderabad District' },
      { code: '06', name: 'Rangareddy' },
      { code: '07', name: 'Mahabubnagar' },
      { code: '08', name: 'Nalgonda' },
      { code: '09', name: 'Warangal' },
      { code: '10', name: 'Khammam' },
    ],
  },
  {
    stateName: 'Andhra Pradesh',
    stateId: 37,
    districts: [
      { code: '01', name: 'Srikakulam' },
      { code: '02', name: 'Vizianagaram' },
      { code: '03', name: 'Visakhapatnam' },
      { code: '04', name: 'East Godavari' },
      { code: '05', name: 'West Godavari' },
      { code: '06', name: 'Krishna' },
      { code: '07', name: 'Guntur' },
      { code: '08', name: 'Prakasam' },
      { code: '09', name: 'Nellore' },
      { code: '10', name: 'Kadapa' },
      { code: '11', name: 'Kurnool' },
      { code: '12', name: 'Ananthapur' },
      { code: '13', name: 'Chittoor' },
    ],
  },
  {
    stateName: 'Lakshadweep',
    stateId: 31,
    districts: [{ code: '01', name: 'Lakshadweep' }],
  },
  {
    stateName: 'Karnataka',
    stateId: 29,
    districts: [
      { code: '01', name: 'Belgaum' },
      { code: '02', name: 'Bagalkot' },
      { code: '03', name: 'Bijapur' },
      { code: '04', name: 'Bidar' },
      { code: '05', name: 'Raichur' },
      { code: '06', name: 'Koppal' },
      { code: '07', name: 'Gadag' },
      { code: '08', name: 'Dharwad' },
      { code: '09', name: 'Uttara Kannada' },
      { code: '10', name: 'Haveri' },
      { code: '11', name: 'Bellary' },
      { code: '12', name: 'Chitradurga' },
      { code: '13', name: 'Davanagere' },
      { code: '14', name: 'Shimoga' },
      { code: '15', name: 'Udupi' },
      { code: '16', name: 'Chikmagalur' },
      { code: '17', name: 'Tumkur' },
      { code: '18', name: 'Bangalore' },
      { code: '19', name: 'Mandya' },
      { code: '20', name: 'Hassan' },
      { code: '21', name: 'Dakshina Kannada' },
      { code: '22', name: 'Kodagu' },
      { code: '23', name: 'Mysore' },
      { code: '24', name: 'Chamarajanagar' },
      { code: '25', name: 'Gulbarga' },
      { code: '26', name: 'Yadgir' },
      { code: '27', name: 'Kolar' },
      { code: '28', name: 'Chikkaballapura' },
      { code: '29', name: 'Bangalore Rural' },
      { code: '30', name: 'Ramanagara' },
    ],
  },
  {
    stateName: 'Puducherry',
    stateId: 34,
    districts: [
      { code: '01', name: 'YANAM' },
      { code: '02', name: 'Puducherry' },
      { code: '03', name: 'MAHE' },
      { code: '04', name: 'Karaikal' },
    ],
  },
  {
    stateName: 'Andaman & Nicobar',
    stateId: 35,
    districts: [
      { code: '01', name: 'Nicobars' },
      { code: '02', name: 'North & Middle Andaman' },
      { code: '03', name: 'South Andaman' },
    ],
  },
  {
    stateName: 'Chhattisgarh',
    stateId: 22,
    districts: [
      { code: '01', name: 'Koriya' },
      { code: '02', name: 'Surguja' },
      { code: '03', name: 'Jashpur' },
      { code: '04', name: 'Raigarh' },
      { code: '05', name: 'Korba' },
      { code: '06', name: 'Janjgir - Champa' },
      { code: '07', name: 'Bilaspur' },
      { code: '08', name: 'Kabeerdham' },
      { code: '09', name: 'Rajnandgaon' },
      { code: '10', name: 'Durg' },
      { code: '11', name: 'Raipur' },
      { code: '12', name: 'Mahasamund' },
      { code: '13', name: 'Dhamtari' },
      { code: '14', name: 'Uttar Bastar Kanker' },
      { code: '15', name: 'Bastar' },
      { code: '16', name: 'Narayanpur' },
      { code: '17', name: 'Dakshin Bastar Dantewada' },
      { code: '18', name: 'Bijapur' },
    ],
  },
  {
    stateName: 'Madhya Pradesh',
    stateId: 23,
    districts: [
      { code: '01', name: 'Sheopur' },
      { code: '02', name: 'Morena' },
      { code: '03', name: 'Bhind' },
      { code: '04', name: 'Gwalior' },
      { code: '05', name: 'Datia' },
      { code: '06', name: 'Shivpuri' },
      { code: '07', name: 'Tikamgarh' },
      { code: '08', name: 'Chhatarpur' },
      { code: '09', name: 'Panna' },
      { code: '10', name: 'Sagar' },
      { code: '11', name: 'Damoh' },
      { code: '12', name: 'Satna' },
      { code: '13', name: 'Rewa' },
      { code: '14', name: 'Umaria' },
      { code: '15', name: 'Neemuch' },
      { code: '16', name: 'Mandsaur' },
      { code: '17', name: 'Ratlam' },
      { code: '18', name: 'Ujjain' },
      { code: '19', name: 'Shajapur' },
      { code: '20', name: 'Dewas' },
      { code: '21', name: 'Dhar' },
      { code: '22', name: 'Indore' },
      { code: '23', name: 'West Nimar' },
      { code: '24', name: 'Barwani' },
      { code: '25', name: 'Rajgarh' },
      { code: '26', name: 'Vidisha' },
      { code: '27', name: 'Bhopal' },
      { code: '28', name: 'Sehore' },
      { code: '29', name: 'Raisen' },
      { code: '30', name: 'Betul' },
      { code: '31', name: 'Harda' },
      { code: '32', name: 'Hoshangabad' },
      { code: '33', name: 'Katni' },
      { code: '34', name: 'Jabalpur' },
      { code: '35', name: 'Narsimhapur' },
      { code: '36', name: 'Dindori' },
      { code: '37', name: 'Mandla' },
      { code: '38', name: 'Chhindwara' },
      { code: '39', name: 'Seoni' },
      { code: '40', name: 'Balaghat' },
      { code: '41', name: 'Guna' },
      { code: '42', name: 'Ashoknagar' },
      { code: '43', name: 'Shahdol' },
      { code: '44', name: 'Anuppur' },
      { code: '45', name: 'Sidhi' },
      { code: '46', name: 'Singrauli' },
      { code: '47', name: 'Jhabua' },
      { code: '48', name: 'Alirajpur' },
      { code: '49', name: 'East Nimar' },
      { code: '50', name: 'Burhanpur' },
    ],
  },
  {
    stateName: 'Gujarat',
    stateId: 24,
    districts: [
      { code: '01', name: 'Kachchh' },
      { code: '02', name: 'Banas Kantha' },
      { code: '03', name: 'Patan' },
      { code: '04', name: 'Mahesana' },
      { code: '05', name: 'Sabar Kantha' },
      { code: '06', name: 'Gandhinagar' },
      { code: '07', name: 'Ahmadabad' },
      { code: '08', name: 'Surendranagar' },
      { code: '09', name: 'Rajkot' },
      { code: '10', name: 'Jamnagar' },
      { code: '11', name: 'Porbandar' },
      { code: '12', name: 'Junagadh' },
      { code: '13', name: 'Amreli' },
      { code: '14', name: 'Bhavnagar' },
      { code: '15', name: 'Anand' },
      { code: '16', name: 'Kheda' },
      { code: '17', name: 'Panch Mahals' },
      { code: '18', name: 'Dohad' },
      { code: '19', name: 'Vadodara' },
      { code: '20', name: 'Narmada' },
      { code: '21', name: 'Bharuch' },
      { code: '22', name: 'The Dangs' },
      { code: '23', name: 'Navsari' },
      { code: '24', name: 'Valsad' },
      { code: '25', name: 'Surat' },
      { code: '26', name: 'Tapi' },
    ],
  },
  {
    stateName: 'Dadra & Nagar Haveli',
    stateId: 26,
    districts: [{ code: '01', name: 'Dadra & Nagar Haveli' }],
  },
  {
    stateName: 'Maharashtra',
    stateId: 27,
    districts: [
      { code: '01', name: 'Nandurbar' },
      { code: '02', name: 'Dhule' },
      { code: '03', name: 'Jalgaon' },
      { code: '04', name: 'Buldana' },
      { code: '05', name: 'Akola' },
      { code: '06', name: 'Washim' },
      { code: '07', name: 'Amravati' },
      { code: '08', name: 'Wardha' },
      { code: '09', name: 'Nagpur' },
      { code: '10', name: 'Bhandara' },
      { code: '11', name: 'Gondiya' },
      { code: '12', name: 'Gadchiroli' },
      { code: '13', name: 'Chandrapur' },
      { code: '14', name: 'Yavatmal' },
      { code: '15', name: 'Nanded' },
      { code: '16', name: 'Hingoli' },
      { code: '17', name: 'Parbhani' },
      { code: '18', name: 'Jalna' },
      { code: '19', name: 'Aurangabad' },
      { code: '20', name: 'Nashik' },
      { code: '21', name: 'Thane' },
      { code: '22', name: 'Mumbai Suburban' },
      { code: '23', name: 'Mumbai' },
      { code: '24', name: 'Raigarh' },
      { code: '25', name: 'Pune' },
      { code: '26', name: 'Ahmadnagar' },
      { code: '27', name: 'Bid' },
      { code: '28', name: 'Latur' },
      { code: '29', name: 'Osmanabad' },
      { code: '30', name: 'Solapur' },
      { code: '31', name: 'Satara' },
      { code: '32', name: 'Ratnagiri' },
      { code: '33', name: 'Sindhudurg' },
      { code: '34', name: 'Kolhapur' },
      { code: '35', name: 'Sangli' },
    ],
  },
  {
    stateName: 'Goa',
    stateId: 30,
    districts: [
      { code: '01', name: 'North Goa' },
      { code: '02', name: 'South Goa' },
    ],
  },
  {
    stateName: 'Daman & Diu',
    stateId: 26,
    districts: [
      { code: '01', name: 'Diu' },
      { code: '02', name: 'Daman' },
    ],
  },
  {
    stateName: 'Ladakh',
    stateId: 38,
    districts: [
      { code: '01', name: 'Leh' },
      { code: '02', name: 'Kargil' },
    ],
  },
];

async function seedDistricts() {
  console.log('🗺️ Seeding all official 600+ Districts into master_districts with stateId FK...');
  let totalCount = 0;

  for (const group of districtsByState) {
    const stateRecord = await prisma.masterState.findUnique({
      where: { id: group.stateId },
    });

    if (!stateRecord) {
      console.warn(`  ⚠️ State ID ${group.stateId} (${group.stateName}) not found in master_states!`);
      continue;
    }

    for (const d of group.districts) {
      const districtCode = `DIS_ST${group.stateId.toString().padStart(2, '0')}_${d.code}`;
      const districtRecord = await prisma.masterDistrict.upsert({
        where: { districtCode },
        update: {
          districtName: d.name,
          stateId: stateRecord.id,
          isActive: true,
          isDeleted: false,
        },
        create: {
          districtCode,
          districtName: d.name,
          stateId: stateRecord.id,
          isActive: true,
          isDeleted: false,
        },
      });

      // Seed default block for this district
      const blockCode = `BLK_${districtCode}_01`;
      const blockName = `${d.name} Block`;
      await prisma.masterBlock.upsert({
        where: { blockCode },
        update: {
          blockName,
          districtId: districtRecord.id,
          isActive: true,
          isDeleted: false,
        },
        create: {
          blockCode,
          blockName,
          districtId: districtRecord.id,
          isActive: true,
          isDeleted: false,
        },
      });

      totalCount++;
    }
    console.log(`  ✓ State ID ${group.stateId.toString().padStart(2, '0')} (${stateRecord.stateName}): Seeded ${group.districts.length} districts.`);
  }

  console.log(`\n🎉 SEEDED ${totalCount} DISTRICTS AND BLOCKS INTO DATABASE WITH STATE FK LINK!`);
}

seedDistricts()
  .catch((e) => {
    console.error('❌ Error seeding districts:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
